### ISSUE TITLE
Status expensive 

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/dugite-extra#10]
For huge pending changes the logic here :
https://github.com/theia-ide/dugite-extra/blob/master/src/command/status.ts#L79
is very expensive.

<img width="775" alt="screen shot 2018-01-15 at 11 08 21" src="https://user-images.githubusercontent.com/372735/34937237-6fe78fa6-f9e4-11e7-9ab2-061eb7851d1a.png">

**Comment by kittaakos** [comment]
Thanks for measuring, I look into it.

**Comment by kittaakos** [comment]
Current status: `calculating 14836 number of changes took 1427 ms.`.

**Comment by svenefftinge** [comment]
I think I had even more than that. 
I accidentally initialized a git repo in my container folder where i have all the locally cloned repos :-)

**Comment by kittaakos** [comment]
The fix seems to be very simple. I have already down to 180-200ms locally (instead of the ~1500ms). I just need to verify it with a few test.
