### ISSUE TITLE
Try to update to Git 2.19

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/dugite-extra#24]
The `CURL_OPENSSL_3` (https://github.com/theia-ide/dugite-extra/issues/21)  issue might have been resolved, cf. https://github.com/desktop/dugite-native/issues/109#issuecomment-433048020.

We should try to use `dugite 1.79.0` on Ubuntu 18.04 and `pull` / `push` works, it should be fine to update.

**Comment by kittaakos** [comment]
I will do an update soon. Does it make sense to bump it up?

**Comment by AlexTugarev** [comment]
Before bumping the version, I'd rather have a test like what we did last time.

On newer Ubuntu (docker should be easiest) 
 1. install latest dugite
 2. cd into directory of embedded git 
 3. try out git: pull and push should work (they use curl lib)

**Comment by kittaakos** [comment]
Is this still relevant, @AlexTugarev?

**Comment by AlexTugarev** [comment]
I think this is outdated, as we're no longer using the embedded git. Sorry for leaving the mess around.
