### ISSUE TITLE
Is it compatible with node 12?

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/dugite-extra#35]
I am trying to build Theia with the current LTS version of Node.js - 12.17.0, and an error shows that
>dugite-extra@0.1.12: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <12". Got "12.16.1"

May I ask, is `dugite-extra` compatible with Node.js v12.17.0?

**Comment by kittaakos** [comment]
I am on it. I am planning to roll out a new release with #33, #34, and #36 soon.

**Comment by benjamin-taheri** [comment]
I'm getting similar error when running it on Ubuntu 2020. Does anyone have any solution?
