### ISSUE TITLE
Compatibility with Node 14

### ISSUE THREAD

**Issue by AxelRICHARD** [theia-ide/dugite-extra#43]
Hello, I am trying to build Theia with the current LTS version of Node.js - 14.15.4, but the problem seems that dugite-extra is not compatible with Node 13+.

Do you plan to be compatible with Node 14?

Best regards,

**Comment by duncdrum** [comment]
even more problematic `electron-builder` requires node `14+` 

see https://github.com/evolvedbinary/fusion-studio/issues/91

**Comment by vince-fugnitto** [comment]
@msujew @thegecko do you know if there are any plans to maintain and uplift `dugite-extra`? As far as I understand it is only used for applications which consume `@theia/git` (which I believe is true for both your cases), and it might be good to uplift as to support newer versions of theia.

**Comment by msujew** [comment]
@vince-fugnitto Yes, we should definitely uplift the dependency (for the time being). I've seen ideas of deprecating `@theia/git` in favor of the appropriate vscode extensions in the future. What's the plan on that?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Yes, we should definitely uplift the dependency (for the time being). I've seen ideas of deprecating `@theia/git` in favor of the appropriate vscode extensions in the future. What's the plan on that?

@msujew that is what we are currently doing, it allows us to use git-related extensions such as `gitlens`. As for removing it as part of the framework (or deprecating it) there is the following issue https://github.com/eclipse-theia/theia/issues/7482. I believe Arm was planning on moving functionality they required out of it: https://github.com/eclipse-theia/theia/issues/7152.

**Comment by msujew** [comment]
I've updated `dugite-extra` to `0.1.15` removing the node constraint. I'll close this.
